### ISSUE TITLE
[Feature] Warning command

### ISSUE THREAD

**Issue by MidNightFrance** [yewshanooi/sodium#35]
Warnings command to see warn of a user

**Comment by Manzanitabot123** [comment]
For this command you need a database that stores the message, user and date of a user's warnings and how many they have with `/see warnings <@user>`, which still needs to be added (database), but it seems like a good idea to me feature and properly I will take it into account for future versions. Thank you @MidNightFrance .

**Comment by yewshanooi** [comment]
Aside from that, it will also require the bot owner to host the database on their machine locally or through the cloud too

**Comment by yewshanooi** [comment]
This feature was added quite long ago using MongoDB Atlas to store the server's logs (which include warnings of users). The staff of a particular server may view the logs using the `/logs view` subcommand). My bad, I didn't check the Issues tab to update this thread. Anyway, thanks again @MidNightFrance for your suggestion.
